DROP TABLE IF EXISTS pepe CASCADE;

CREATE TABLE pepe (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	name VARCHAR(255) NOT NULL,
	url VARCHAR(255) NOT NULL,
	http_code VARCHAR(255) NOT NULL
);

insert into pepe (name, url, http_code) values ('Continue','https://cdn.7tv.app/emote/620ebe5721b4d5de1446e18e/4x.avif', '100');
insert into pepe (name, url, http_code) values ('Switching Protocols','https://cdn.7tv.app/emote/60ef410f48cde2fcc3eb5caa/4x.avif', '101');
insert into pepe (name, url, http_code) values ('Processing','https://cdn.7tv.app/emote/6154d7d86251d7e000db1727/4x.avif', '102');
insert into pepe (name, url, http_code) values ('Early Hints','https://cdn.7tv.app/emote/62262a76b825598c205cddcf/4x.avif', '103');
insert into pepe (name, url, http_code) values ('Ok','https://cdn.7tv.app/emote/6268904f4f54759b7184fa72/4x.avif', '200');
insert into pepe (name, url, http_code) values ('Created','https://cdn.7tv.app/emote/610eaccf900cbd77c6958454/4x.avif', '201');
insert into pepe (name, url, http_code) values ('Accepted','https://cdn.7tv.app/emote/61ee92664eb7aade4ad32f15/4x.avif', '202');
insert into pepe (name, url, http_code) values ('Non-authoritative information','https://cdn.7tv.app/emote/62e4d149e0e9f736c5174b87/4x.avif', '203');
insert into pepe (name, url, http_code) values ('No Content','https://cdn.7tv.app/emote/60c107ee69996caa387ee117/4x.avif', '204');
insert into pepe (name, url, http_code) values ('Reset Content','https://cdn.7tv.app/emote/62503d556bb22d4119fc9060/4x.avif', '205');
insert into pepe (name, url, http_code) values ('Partial Content','https://cdn.7tv.app/emote/65c3abb895692648d1824ca9/4x.webp', '206');
insert into pepe (name, url, http_code) values ('Multi-status','https://cdn.7tv.app/emote/6263e65d5e7fcb2e46bb6542/4x.avif', '207');
insert into pepe (name, url, http_code) values ('Already Reported','https://cdn.7tv.app/emote/65e90eec874a802d76b0b179/4x.avif', '208');
insert into pepe (name, url, http_code) values ('Transformation Applied','https://cdn.7tv.app/emote/632e2cee2cfbb9c4a9957cf1/4x.avif', '214');
insert into pepe (name, url, http_code) values ('IM Used','https://cdn.7tv.app/emote/60ba5ddaca899d6c6dcd9388/4x.avif', '226');
insert into pepe (name, url, http_code) values ('Multiple Choices','https://cdn.7tv.app/emote/652b744625df580cafd19771/4x.avif', '300');
insert into pepe (name, url, http_code) values ('Moved Permanently','https://cdn.7tv.app/emote/61b369cd8ffada6c4baf55fb/4x.avif', '301');
insert into pepe (name, url, http_code) values ('Found','https://cdn.7tv.app/emote/64794103804ca09ebf23b285/4x.avif', '302');
insert into pepe (name, url, http_code) values ('See Other','https://cdn.7tv.app/emote/60aea6c3f39a7552b63d50a3/4x.avif', '303');
insert into pepe (name, url, http_code) values ('Not Modified','https://cdn.7tv.app/emote/604137d3cf6746000db10354/4x.avif', '304');
insert into pepe (name, url, http_code) values ('Use Proxy','https://cdn.7tv.app/emote/60cf6d6a4011650f01e0c82f/4x.avif', '305');
insert into pepe (name, url, http_code) values ('Temporary Redirect','https://cdn.7tv.app/emote/6106032b962f9581ec39379c/4x.avif', '307');
insert into pepe (name, url, http_code) values ('Permanent Redirect','https://cdn.7tv.app/emote/64053991cb4fca4bfe6ddc7c/4x.avif', '308');
insert into pepe (name, url, http_code) values ('Bad Request','https://cdn.7tv.app/emote/63ac0477d2d658beab6246c5/4x.avif', '400');
insert into pepe (name, url, http_code) values ('Unauthorized','https://cdn.7tv.app/emote/613e4883962a6090486421ac/4x.avif', '401');
insert into pepe (name, url, http_code) values ('Payment Required','https://cdn.7tv.app/emote/60aee8087e8706b572cf37f3/4x.avif', '402');
insert into pepe (name, url, http_code) values ('Forbidden','https://cdn.7tv.app/emote/6125775d0c9f70780af19dcc/4x.avif', '403');
insert into pepe (name, url, http_code) values ('Not Found','https://cdn.7tv.app/emote/61e71d7a77175547b425ed73/4x.avif', '404');
insert into pepe (name, url, http_code) values ('Method Not Allowed','https://cdn.7tv.app/emote/60b052b06862c44dce30a469/4x.avif', '405');
insert into pepe (name, url, http_code) values ('Not Acceptable','https://cdn.7tv.app/emote/61819b26f1ae15abc7eb8f66/4x.avif', '406');
insert into pepe (name, url, http_code) values ('Proxy Authentication Required','https://cdn.7tv.app/emote/6143bb1d962a60904864c20f/4x.avif', '407');
insert into pepe (name, url, http_code) values ('Request Timeout','https://cdn.7tv.app/emote/621c1d047f7ec26e095e1b41/4x.avif', '408');
insert into pepe (name, url, http_code) values ('Conflict','https://cdn.7tv.app/emote/617ad372c632476d20d03526/4x.avif', '409');
insert into pepe (name, url, http_code) values ('Gone','https://cdn.7tv.app/emote/60d22953f8d13796245b6ca2/4x.avif', '410');
insert into pepe (name, url, http_code) values ('Length Required','https://cdn.7tv.app/emote/60f781a9e57bec0216aba7ec/4x.avif', '411');
insert into pepe (name, url, http_code) values ('Precondition Failed','https://cdn.7tv.app/emote/60fcd2d93acb2bea43365fa8/4x.avif', '412');
insert into pepe (name, url, http_code) values ('Payload Too Large','https://cdn.7tv.app/emote/634493ce05c2b2cd864d5f0d/4x.avif', '413');
insert into pepe (name, url, http_code) values ('Uri Too Long','https://cdn.7tv.app/emote/62547b9cb0dfc5aeb040c716/4x.avif	', '414');
insert into pepe (name, url, http_code) values ('Unsupported Media Type','https://cdn.7tv.app/emote/63cfefc32658f27cb875215f/4x.avif', '415');
insert into pepe (name, url, http_code) values ('Range Not Satisfiable','https://cdn.7tv.app/emote/620a7fb7baa1c8458762f23d/4x.avif', '416');
insert into pepe (name, url, http_code) values ('Expectation Failed','https://cdn.7tv.app/emote/60ae6a7b117ec68ca434404e/4x.avif', '417');
insert into pepe (name, url, http_code) values ('Im A Teapot','https://cdn.7tv.app/emote/610eb864150eeac172e372c8/4x.avif', '418');
insert into pepe (name, url, http_code) values ('Misdirected Request','https://cdn.7tv.app/emote/643ff45839b7f46dd13e08b5/4x.avif', '421');
insert into pepe (name, url, http_code) values ('Unprocessable Entity','https://cdn.7tv.app/emote/60b885525d373afbd6d85264/4x.avif', '422');
insert into pepe (name, url, http_code) values ('Locked','https://cdn.7tv.app/emote/630f73935b7c06647dac696b/4x.avif', '423');
insert into pepe (name, url, http_code) values ('Failed Dependency','https://cdn.7tv.app/emote/642793cc8b73496c8c83773f/4x.avif', '424');
insert into pepe (name, url, http_code) values ('Too Early','https://cdn.7tv.app/emote/64de57da6503f02368265ee3/4x.avif', '425');
insert into pepe (name, url, http_code) values ('Upgrade Required','https://cdn.7tv.app/emote/618bd18dd34608492cc29ac1/4x.avif', '426');
insert into pepe (name, url, http_code) values ('Precondition Required','https://cdn.7tv.app/emote/614fa7f320eaf897465a692b/4x.avif', '428');
insert into pepe (name, url, http_code) values ('Too Many Requests','https://cdn.7tv.app/emote/64f12483731bb225931239f8/4x.avif', '429');
insert into pepe (name, url, http_code) values ('Request Header Fields Too Large','https://cdn.7tv.app/emote/635298d971fa45229834ebd8/4x.avif', '431');
insert into pepe (name, url, http_code) values ('Unavailable For Legal Reasons','https://cdn.7tv.app/emote/61eb352e009502d85be4db97/4x.avif', '451');
insert into pepe (name, url, http_code) values ('Internal Server Error','https://cdn.7tv.app/emote/6109980cc5ccdd7baf4f5579/4x.avif', '500');
insert into pepe (name, url, http_code) values ('Not Implemented','https://cdn.7tv.app/emote/64e43d7716fd37f6aaf8d741/4x.avif', '501');
insert into pepe (name, url, http_code) values ('Bad Gateway','https://cdn.7tv.app/emote/63066cd30e929d2fde44ddc8/4x.avif', '502');
insert into pepe (name, url, http_code) values ('Service Unavailable','https://cdn.7tv.app/emote/61ca63abef5a587a0745c7c9/4x.avif', '503');
insert into pepe (name, url, http_code) values ('Gateway Timeout','https://cdn.7tv.app/emote/631351a3113e0e8575d2effc/4x.avif', '504');
insert into pepe (name, url, http_code) values ('Http Version Not Supported','https://cdn.7tv.app/emote/61dc708757c70f633ebd8bf9/4x.avif', '505');
insert into pepe (name, url, http_code) values ('Variant Also Negotiates','https://cdn.7tv.app/emote/6256277ab0dfc5aeb040e6f8/4x.avif', '506');
insert into pepe (name, url, http_code) values ('Insufficient Storage','https://cdn.7tv.app/emote/624764c1246dc2359f682b30/4x.avif', '507');
insert into pepe (name, url, http_code) values ('Loop Detected','https://cdn.7tv.app/emote/63bf4406c97fab9acc06b0a1/4x.avif', '508');
insert into pepe (name, url, http_code) values ('Not Extended','https://cdn.7tv.app/emote/61761ddf5ff09767de2a3795/4x.avif', '510');
insert into pepe (name, url, http_code) values ('Network Authentication Required','https://cdn.7tv.app/emote/648a25925fd61ff3503cffac/4x.avif', '511');
insert into pepe (name, url, http_code) values ('Site Frozen','https://cdn.7tv.app/emote/61ef76741300d0c637b92f82/4x.avif', '530');
